import type { NextPage } from 'next'
import Image from 'next/image'
import Head from 'next/head'

import { Container, Section, MidSection } from '../styles/home'
import JJImage from '../assets/logos/JJ.svg'
import { Tags } from '../components/Tags'
import Hero from '../assets/hero.svg'

const Home: NextPage = () => {
    return (
        <Container>
            <Head>
                <title>Home | Joel Sena</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <Tags
                tags={[
                    { content: "<html lang='pt-BR'>" },
                    { content: '<body>', hierarchy: 'second' }
                ]}
                wrapPad
            />

            <Section>
                <MidSection>
                    <Tags tags={[{ content: '<h1>' }]} />
                    <h1>Olá,</h1>

                    <h1>
                        Sou <Image src={JJImage} alt="JJ" width={52} />
                        oel,
                    </h1>

                    <h1>Web Developer</h1>
                    <Tags tags={[{ content: '</h1>' }]} />

                    <Tags tags={[{ content: '<p>' }]} />
                    <p>Front End Developer / Researcher</p>
                    <Tags tags={[{ content: '</p>' }]} />
                </MidSection>

                <MidSection>
                    <Image
                        src={Hero}
                        alt="Minha Imagem"
                        layout="responsive"
                        // placeholder="blur"
                    />
                </MidSection>
            </Section>

            <Tags
                tags={[
                    { content: '</body>', hierarchy: 'second' },
                    { content: '<html>' }
                ]}
                wrapPad
            />
        </Container>
    )
}

export default Home
